# Generated by Django 5.0.4 on 2024-05-01 01:48

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_date', models.DateField(default=django.utils.timezone.now)),
                ('package', models.CharField(max_length=35)),
                ('validity', models.DateField(default=payments.models.Subscription.calculate_validity)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
