# Generated by Django 5.0.4 on 2024-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='projects_left',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
