# Generated by Django 5.0.4 on 2024-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_projects_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='projects_left',
            field=models.IntegerField(default=10),
        ),
    ]
