# Generated by Django 5.0.4 on 2024-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_invoice_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='package',
            new_name='package_name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='package_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
