# Generated by Django 5.0.4 on 2024-05-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_package_subscription_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
