# Generated by Django 5.0.4 on 2024-05-23 12:48

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscription_subscribed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='validity',
            field=models.DateField(default=payments.models.Subscription.calculate_validity),
        ),
    ]
