# Generated by Django 5.0.4 on 2024-05-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_subscription_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='validity',
            field=models.DateField(),
        ),
    ]
