# Generated by Django 5.0.4 on 2024-05-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_subscription_validity'),
        ('projects', '0009_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('advance', 'advance'), ('final', 'final')], max_length=20)),
                ('invoice_url', models.URLField(help_text='Invoice URL')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='freelancer_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=155)),
                ('advance_pricing_id', models.CharField(max_length=155)),
                ('final_pricing_id', models.CharField(max_length=155)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
        ),
    ]
