# Generated by Django 5.0.4 on 2024-05-23 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_freelancerpayments_stripeproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='freelancer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancerpayments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freelancerpayments',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freelancer_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
