# Generated by Django 5.0.4 on 2024-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_stripeproduct_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpayments',
            name='invoice_url',
            field=models.URLField(blank=True, help_text='Invoice URL', null=True),
        ),
    ]
