# Generated by Django 5.0.4 on 2024-05-24 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_freelancerpayments_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpayments',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
