# Generated by Django 5.0.4 on 2024-05-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_freelancerpayments_payment_date'),
        ('projects', '0010_project_is_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerpayments',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.proposals'),
            preserve_default=False,
        ),
    ]
