# Generated by Django 5.0.4 on 2024-05-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_freelancerpayments_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeproduct',
            name='is_advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripeproduct',
            name='is_final_paid',
            field=models.BooleanField(default=False),
        ),
    ]
