# Generated by Django 5.0.4 on 2024-05-28 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_stripeproduct_is_advance_paid_and_more'),
        ('projects', '0011_proposals_is_advance_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreelancerPayments',
            new_name='ProjectPayments',
        ),
    ]
