# Generated by Django 5.0.4 on 2024-05-28 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_rename_freelancerpayments_projectpayments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayments',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_payments_freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
