# Generated by Django 5.0.4 on 2024-05-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_freelancerpayouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerpayouts',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='freelancerpayouts',
            name='project',
        ),
    ]
