# Generated by Django 5.0.4 on 2024-05-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_remove_freelancerpayouts_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerpayouts',
            old_name='client_payment_details',
            new_name='payment_details',
        ),
    ]
