# Generated by Django 5.0.4 on 2024-05-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_rename_client_payment_details_freelancerpayouts_payment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerpayouts',
            old_name='payment_details',
            new_name='client_payment_details',
        ),
    ]
