# Generated by Django 4.1.13 on 2024-04-18 04:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=115), null=True, size=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=projects.models.Project.default_deadline)),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting'), ('progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('hold', 'On Hold')], default='recruiting', max_length=20)),
                ('freelancer_expertise', models.CharField(choices=[('entry_level', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='freelancer_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
