# Generated by Django 4.1.13 on 2024-04-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_savedprojects_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proposals',
            name='document',
            field=models.FileField(null=True, upload_to='project_applications/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer_expertise',
            field=models.CharField(choices=[('entry_level', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20, null=True),
        ),
    ]
