# Generated by Django 5.0.4 on 2024-05-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_proposals_cover_letter_proposals_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='status',
            field=models.CharField(choices=[('unanswered', 'Unanswered'), ('responded', 'Responded'), ('accepted', 'Accepted')], max_length=20),
        ),
    ]
