# Generated by Django 5.0.4 on 2024-05-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_proposals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='status',
            field=models.CharField(choices=[('unanswered', 'Unanswered'), ('responded', 'Responded'), ('accepted', 'Accepted')], default='unanswered', max_length=20),
        ),
    ]
