# Generated by Django 5.0.4 on 2024-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_advance_paid',
            field=models.BooleanField(default=False),
        ),
    ]
