# Generated by Django 5.0.4 on 2024-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_proposals_is_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_final_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_sample_completed',
            field=models.BooleanField(default=False),
        ),
    ]
