# Generated by Django 4.1.13 on 2024-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_profile', models.CharField(max_length=255)),
                ('listing_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='portfolio_images')),
            ],
        ),
    ]
