# Generated by Django 4.1.13 on 2024-04-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='listing_id',
        ),
    ]
